### PR TITLE
Let configure know where ncurses is

### PR DESCRIPTION
**Pull request by ggreif**
~~It builds its own otherwise?~~

### CODE REVIEW

**Comment by supersven** [comment]
Hey @ggreif ,

Thanks for your PR!

This sounds a bit surprising to me. May I asked how you figured that out? :thinking:

**Comment by ggreif** [comment]
The only way to communicate the location of libraries to the build is by envvars. Let me point out the difference in terms of the `config.log`:

-- TO BE ADDED --

**Comment by ggreif** [comment]
There is still a deficiency in GHC's `FP_CURSES` autoconf definition,  as it won't accept `--with-curses-includes`, but that's another battle.

**Comment by supersven** [comment]
@ggreif ,

Thanks for the explanation!

The change looks reasonable, I will just quickly check it on my machine.

I was just wondering if GHC really builds it's own ncurses lib (under circumstances), but maybe I misunderstood this part ... :thinking:

**Comment by ggreif** [comment]
I think I mixed that part up, and I thought about `gmp`. I have never seen an in-tree `ncurses`.

**Comment by ggreif** [comment]
Looks like the headers are not interesting any more: https://gitlab.haskell.org/ghc/ghc/-/commit/ef63ff27251a20ff11e58c9303677fa31e609a88

**Comment by supersven** [comment]
Okay :smiley: 

Thanks for investigating this.

**Pull request merged**
