### PR TITLE
flakify

### PR DESCRIPTION
**Pull request by MangoIV**
Offers to use this repo with the (still experimental) flake commands. 
To have backwards compatibility, the flake inputs only pin the `nixpkgs` and `nixpkgs-unstable`. 

This PR is an alternative proposal to #121 , its advantages are that 
- we don't require to pass `--impure`
- we don't depend on `flake-utils`
- I also included a formatter in the `outputs` which can be run with `nix fmt` and admittedly makes the diff horrible, please excuse that.

### CODE REVIEW

**Comment by sgraf812** [comment]
I can confirm that this patch works. 

I noticed that it also takes quite a while to build. Not sure if it's longer than currently on master, though, and that could probably be fixed in isolation.

I like that I can finally do `nix develop` and replace all the `lorri+direnv` stuff I used to do with a much simpler `.envrc`.

**Comment by MangoIV** [comment]
> I noticed that it also takes quite a while to build. Not sure if it's longer than currently on master, though, and that could probably be fixed in isolation.

it's possible that's the case because we now have *both* niv and nix' own dependency resolution as an extra step, would you be able to try #132 and compare it with that? (It's also more up to date). The latter gets rid of niv entirely so it comes down to whether nix' flake or builtins fetcher impls (and nivs wrapper around those) is quicker.

**Comment by sgraf812** [comment]
Thanks, I'll give it a try. Although I haven't high hopes because it's mostly building Haskell libraries, not so much dependency resolution. I see that it's rebuilding `alex`, `Cabal`, `network`, a `texlive` distribution, ... But perhaps that is no different to current master, looking at default.nix.

**Comment by MangoIV** [comment]
it's also possible that's the case because it's not yet cached on the cachix (no ci run on this branch since my last commit)...
The other one should have the same problem then. If this (or #132 for that matter) gets merged it will be faster.

**Comment by MangoIV** [comment]
Has been superceded by #132

**Pull request closed without merging**
