### PR TITLE
js: add unstable output, set nodejs to nodejs_21

### PR DESCRIPTION
**Pull request by doyougnu**
- This change aligns the ghc.nix nodejs version to the node version that runs on GHC's CI. See commit 23d72bc7674e643c73256242ba781bea4aef4fb8 in ci-images on the GHC gitlab instance.

There still might be some kinks: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/11976#note_546797

draft until then

### CODE REVIEW

**Comment by doyougnu** [comment]
we might be better off just bumping the flake to 23.11 to get nodejs_21. The override will rebuild the emscripten package for each job.

**Comment by doyougnu** [comment]
Done. I added `nodejs` to `.#js-cross` because the nodejs debugger and profiler is useful for debugging programs the js backend compiled.

**Comment by doyougnu** [comment]
`no space left on device`... perhaps adding `unstable` was too much

**Comment by doyougnu** [comment]
Closing, I'll bump the flake instead

**Comment by MangoIV** [comment]
Try to migrate to 23.11 if you can.

**Pull request closed without merging**
