### PR TITLE
Add haskell-language-server as IDE 

### LINKED ISSUE #73: Re-enable ghcide
Looks like `ghcide-nix` now supports GHC 8.8.3. (I haven't tested it, yet, but the related branch was pushed to master this morning.)

That means we can revert the related changes from https://github.com/alpmestan/ghc.nix/pull/65.

### PR DESCRIPTION
**Pull request by sgraf812**
Since haskell/haskell-language-server#122 we have a working HLS-wrapper in nixpkgs 🎉. And it seems to work for just fine for GHC!

Now I only have to set it up correctly...

Anyway, this fixes #73.

### CODE REVIEW

**Comment by sgraf812** [comment]
Well, it turns out that the resulting language server doesn't really work on GHC (yet):

```
$ haskell-language-server-wrapper compiler/GHC/Driver/Main.hs
[...]
Tool versions found on the $PATH
cabal:          3.2.0.0
stack:          2.3.3
ghc:            8.8.4


Step 1/4: Finding files to test in /home/sgraf-local/code/hs/ghc/misc4
Found 1 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
[INFO] Consulting the cradle for "compiler/GHC/Driver/Main.hs"
Output from setting up the cradle Cradle {cradleRootDir = "/home/sgraf-local/code/hs/ghc/misc4", cradleOptsProg = CradleAction: Bios}
> hadrian: .hie-bios/hadrian/.shake.database: hSetFileSize: illegal operation (handle is closed)
File:     /home/sgraf-local/code/hs/ghc/misc4/compiler/GHC/Driver/Main.hs
Hidden:   no
Range:    1:0-2:0
Source:   cradle
Severity: DsError
Message:
  hadrian: .hie-bios/hadrian/.shake.database: hSetFileSize: illegal operation (handle is closed)
[INFO] finish: User TypeCheck (took 0.26s)
Files that failed:
 * /home/sgraf-local/code/hs/ghc/misc4/compiler/GHC/Driver/Main.hs

Completed (0 files worked, 1 file failed)
haskell-language-server-wrapper: callProcess: /nix/store/i4qnhpd8wk8qfzw7xr97sk1894cbf0ps-haskell-language-server-0.5.0.0/bin/haskell-language-server-8.8.4 "compiler/GHC/Driver/Main.hs" (exit 1): failed
```

**Comment by alpmestan** [comment]
@sgraf812 Thanks for working on bringing this back!

That's quite an obscure error, any idea of what might be going on?

**Comment by sgraf812** [comment]
My disk was simply full. The error was completely unrelated. As of now, I can successfully use HLS with kakoune in the generated nix-shell :tada:

**Comment by supersven** [comment]
LGTM.

I haven't tested it yet, but moving from `ghcide` to `haskell-language-server` seems to be reasonable to me.

Thanks for this PR, @sgraf812 ! 👍

**Comment by alpmestan** [comment]
@sgraf812 Oh my bad I somehow skipped the part about your disk being full earlier, sorry.

**Review by alpmestan — APPROVED** [review]

**Pull request merged**
