### PR TITLE
Add ccls and bear

### PR DESCRIPTION
**Pull request by supersven**
> `ccls` implements the Language Server Protocol for C.
> `bear` generates `compile_commands.json` (JSON Compilation Database) files that are used by `ccls` as configuration.

So, with `withIde = true;` you now get everything you need to get IDE support for `*.c` files (e.g. under `rts/`).

### CODE REVIEW

**Comment by mpickering** [comment]
Did you check this works for the RTS files?

**Comment by supersven** [comment]
Hey @mpickering ,

Yes. This should work for all `*.c` files in the GHC project. I checked some files in `rts/`, `libraries/base/cbits` and `compiler/cbits`.

`*.h` files might show issues, that is because they aren't self-contained; i.e. some make only sense the the context where the pre-processor inlines them...

Have you experienced any problems? 

If yes, was your `compile_commands.json` empty? Unfortunately (until I figure out a better approach), you've to do a full rebuild, so that `bear` can capture all C compiler arguments.

If you want to try it, the setup is described here:
- https://gitlab.haskell.org/ghc/ghc/wikis/Visual-Studio-Code/#build-ghc-with-ghcnix
- https://gitlab.haskell.org/ghc/ghc/wikis/Visual-Studio-Code/#install-ghcide-and-ccls-plugins

**Comment by supersven** [comment]
I've made a small screencast:

[VSCode and ccls](http://www.youtube.com/watch?v=5I4H9b8N36M "VSCode and ccls for the GHC project")

**Comment by alpmestan** [comment]
@mpickering Any "objection"/comment left?

That does look handy for anyone working on the RTS regularly.

**Comment by mpickering** [comment]
My comment is that it looks too annoying to use regularly but if people want to do it..

**Pull request merged**
