### PR TITLE
Add gdb, perf to the shell

### PR DESCRIPTION
**Pull request by TeofilC**
I regularly want these for GHC development and I don't think they add much to the size of the closure.
I'm also happy to put them behind a flag (or two).

### CODE REVIEW

**Comment by MangoIV** [comment]
Valgrind is already hidden behind the flag “withGrind” Id say, add the other two in the same fashion and document them in the flag list ;)

**Comment by TeofilC** [comment]
Oh nice I missed that! I'll do that

**Comment by TeofilC** [comment]
Perhaps I want to add something that installs the gdb plugin from as well https://gitlab.haskell.org/bgamari/ghc-utils/activity. Or that could be a different MR

**Comment by TeofilC** [comment]
I'm closing because this was applied on the Gitlab repo

**Pull request closed without merging**
